### ISSUE TITLE
Add Cantonese support to ZH

### ISSUE THREAD

**Issue by kkpoon** [facebookincubator/duckling#21]
## Situation
In Hong Kong, Cantonese is an official spoken language.
The wording is a bit differ from the formal written Chinese. Yet, a lot of Hong Kong people love typing text in spoken language form.

## What to do
In order to support, adding those keywords Cantonese into ZH would help duckling handle Cantonese wordings.

## Question
Which language code should add the handling into?
For example in `Time`, (1)`Duckling/Time/ZH` or (2) `Duckling/Time/ZH-YUE`?
which wikipedia use `zh-yue` to represent Cantonese content.

**Comment by patapizza** [comment]
As we don't support locales yet, I suggest to extend `ZH`. It looks like Cantonese would go under `ZH_HK`.
