### ISSUE TITLE
Support early/mid/late <month>

### ISSUE THREAD

**Issue by pcgreat** [facebookincubator/duckling#35]
e.g.
early June -> 06/01-06/10
mid June -> 06/11-06/20
late June -> 06/21-06/30

**Comment by patapizza** [comment]
Hi @pcgreat, do you think you can implement this? Thanks!

**Comment by pcgreat** [comment]
@patapizza I will try my best

**Comment by Abhiroop** [comment]
@pcgreat I have the same requirement. Did you make any progress in it? Or I can try picking this up too.

**Comment by pcgreat** [comment]
@Abhiroop I am still reading the source code, and haven't made any real progress yet. You are more than welcome to pick it up

**Comment by serefayar** [comment]
@pcgreat @Abhiroop I am not sure about the implementation.

**Comment by pcgreat** [comment]
@serefayar thanks for your implementation! I did try your commits and it's a good reference for me to learn. However, I notice something weird and not sure if that's something you can fix: "late July" points to the July of 2018. Ideally, "late July" can be July of 2017, and "late February" to be Feb of 2018 (future by default)

**Comment by pcgreat** [comment]
thanks @serefayar Looks perfect!
