### ISSUE TITLE
Help out a dummie?

### ISSUE THREAD

**Issue by mariogintili** [facebookincubator/duckling#36]
Hello guys,

Was wondering if you could provide a screencast/guide on how to setup duckling as a server, adding new entities, etc; allá wit.ai style?

I've recorded [screencasts](https://www.codeschool.com/screencasts/rspec-3-best-practices#comments) before and more than happy to record one for everyone's benefit as long as someone with a bette grasp of the project feels free to help me out 😄

**Comment by patapizza** [comment]
Hey @mariogintili,

We don't provide this right now. If somebody can record screencasts that prove useful to the community, we might add pointers to those.

I'm happy to help regarding specific issues on spinning up a server running Duckling. To setup new dimensions, you can look at the commit history on how to do that. We can definitely do a better job regarding the documentation.

Closing this, feel free to reopen or open new tickets to address specific issues you run against. :)
