### ISSUE TITLE
Parse a relative time from a specific referenceTime

### ISSUE THREAD

**Issue by amenella** [facebookincubator/duckling#37]
Hi everyone,

Would it be possible to parse a time from a specific referenceTime ?
As i understood (let me know if i'm wrong) for now referenceTime is only based on the given timezone.

What I would like to do is to give as input a specific datetime, and get a result from that specific datetime.

For example if my inputs are
```
input: {
  referenceTime: '2017-06-08T15:00:00+02:00',
  text: 'next monday at 8am',
}
```

I would like to get **next monday at 8am from the 8th of june 2017**, that means `2017-06-12T08:00:00+02:00`

Would it be possible ?

Thanks !

**Comment by patapizza** [comment]
Hi @amenella,

This is possible using `fromZonedTime` from `Duckling.Resolve`.

Example running a REPL session: `st repl --no-load`.

```haskell
> :l Duckling.Core
> import qualified Data.Time as Time
> d = Time.fromGregorian 2017 6 8
> tod = Time.TimeOfDay 0 0 0
> lt = Time.LocalTime d tod
> tz = Time.TimeZone 120 False "hmm"
> zt = Time.ZonedTime lt tz
> duckt = fromZonedTime zt
> parse "next monday at 8am" Context {referenceTime = duckt, lang = EN} [This Time]
[Entity {dim = "time", body = "next monday at 8am", value = "{\"values\":[{\"value\":\"2017-06-12T08:00:00.000+02:00\",\"grain\":\"hour\",\"type\":\"value\"}],\"value\":\"2017-06-12T08:00:00.000+02:00\",\"grain\":\"hour\",\"type\":\"value\"}", start = 0, end = 18}]
```

Let me expose `fromZonedTime` in `Duckling.Core`.

**Comment by amenella** [comment]
Thanks for the reply @patapizza

if i'm not missing anything here, after having exposed `fromZonedTime` in `Duckling.Core`, we have to get our custom post param on the server side in `ExampleMain.hs` and then pass it to the context as `referenceTime`.

Am I right ?

Please forgive me if my question are meaningless, I'm just a beginner in haskell...

**Comment by patapizza** [comment]
Yes that's right. :)

Curious about why do timezones not work for you?

**Comment by amenella** [comment]
Timezones are good but in a discussion, context always differs, especially when you're talking about time.
Take this example of conversation *(referenceTime is thursday 1st of june 2017)*
1. Are you free next tuesday ? *(tuesday 6th of june 2017)*
2. No, but I am on the friday. *(friday 9th of june 2017)*

You can note that in `2.` `friday` refers to friday after the next tuesday, so we have to update the referenceTime to the `next tuesday`'s date, that means tesday 6th of june 2017, which was not possible until your commit @patapizza 

Hope it's fullfilling your curiosity ! :)

Thanks again !

**Comment by amenella** [comment]
I'm really struggling with the retrieval of my post param `refTime`.

Here is what I'm trying to do in `ExampleMain.hs`

```
parseHandler :: HashMap Text TimeZoneSeries -> Snap ()
parseHandler tzs = do
  modifyResponse $ setHeader "Content-Type" "application/json"
...
  rt <- getPostParam "refTime"
...
case t of
...
  Just tx -> do
    refZTime <- fromZonedTime $ parseRefZTime rt
...
  where
    parseRefZTime :: Maybe ByteString -> ZonedTime
      parseRefZTime rt = fromMaybe defaultTime $ rt >>=
        readMaybe . Text.unpack . Text.decodeUtf8
```

I would like to set  `defaultTime`'s value to the current time, but I don't know how.

Am I completely wrong ?
Could someone help me out please ? @patapizza ?

**Comment by chiapas** [comment]
> Thanks for the reply @patapizza
> 
> if i'm not missing anything here, after having exposed `fromZonedTime` in `Duckling.Core`, we have to get our custom post param on the server side in `ExampleMain.hs` and then pass it to the context as `referenceTime`.
> 
> Am I right ?
> 
> Please forgive me if my question are meaningless, I'm just a beginner in haskell...

Hi, at the current version, can we directly specify referencetime as augument in the request url? For example, curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_GB&referencetime=XXX&text=tomorrow at eight'

**Comment by patapizza** [comment]
@chiapas: Yes using [reftime](https://github.com/facebook/duckling/blob/master/exe/ExampleMain.hs#L81).
