### ISSUE TITLE
the meaning of latent time

### ISSUE THREAD

**Issue by simon0227** [facebookincubator/duckling#46]
Hi all, 
     What is the meaning of latent time in Duckling? Since the library filters latent time, Duckling fails to recognise "2017年5月" in Chinese (aka. 2017-05). More specifically, the rule `ruleMonthNumericWithMonthSymbol` at line 971 in Duckling/Times/ZH/Rule.hs makes "5月" as latent time. 
    To fix the bug, we can remove the `mkLatent` function in line 981.

However, I still confuse the latent time.  Is there anyone can help me?

Thanks in advance!

**Comment by patapizza** [comment]
Hi @simon0227,

Latent tokens are intermediate layers of final tokens. They potentially hold some information about the dimension, but the information found is not enough to fully express an instance of the dimension (think necessary vs sufficient conditions).

I'm not familiar with Chinese, though it looks like 月 is a symbol that indicates a month. In this case, this shouldn't be latent (as 'May' for English). Updating `ruleMonthNumericWithMonthSymbol` to return a non-latent token would help recognizing "5月" as `Time`.
To recognize "2017年5月" though, it would require an extra rule that takes a year, the symbol 年, and a month (does this make sense?). Strictly speaking, this doesn't require `ruleMonthNumericWithMonthSymbol` to return a non-latent token.

Hope this helps.

**Comment by simon0227** [comment]
Hi @patapizza ,
Thanks for the detailed explanation. 
For the first case, returning a non-latent token does help.

For the second case, as you suggested, adding an extra rule will works. However, the original source code has contained a rule called `ruleIntersect :: Rule`, which require two non-latent Time token. So return a non-latent token from `ruleMonthNumericWithMonthSymbol` also helps.

Therefore, removing the `mkLatent` function may be a good choice.

**Comment by patapizza** [comment]
Oh 年 is the year symbol. Sounds good, let's do that.

**Comment by simon0227** [comment]
Yeah, 年 is the year symbol and 月 is the month symbol.
