### ISSUE TITLE
Amount of money has lossy value type

### ISSUE THREAD

**Issue by robinp** [facebookincubator/duckling#5]
Now the value is a Double, which is subject to floating point imprecision.
Just an idea - maybe (also) store as Integer + exponent?

**Comment by patapizza** [comment]
Hi @robinp,
As far as I'm aware of, the lowest subdivision for currencies is 1/1000, which shouldn't be a problem for `Double`.
Do you have a specific example that does not work?

**Comment by robinp** [comment]
Well, better than Float, that's true. Depends on the domain of currency supported. Wikipedia says Double is fine up to ~15-17 significant digits, so you can pile up a pretty nice sum of money before it gets problematic. 

λ (read "1500000000000.3456") :: Double
1.5000000000003457e12

Feel free to close if not a concern.

**Comment by patapizza** [comment]
Yes, let's close this for now.

**Comment by axman6** [comment]
If you're going to talk about decimal numbers, the Scientific type is generally a much better option than Double, as they're stored as an integer + base 10 exponent already. This is already used in the Aeson library, so doesn't add any actual new deps - there's no reason a tool like this should fail with the above examples

```haskell
Prelude> import Data.Scientific
Prelude Data.Scientific> (read "1500000000000.3456") :: Double
1.5000000000003457e12
Prelude Data.Scientific> (read "1500000000000.3456") :: Scientific 
1.5000000000003456e12
Prelude Data.Scientific> 
```
