### ISSUE TITLE
"last weekend of october"

### ISSUE THREAD

**Issue by tarung-ml** [facebookincubator/duckling#50]
This returns: a weekend of october from last year (2016). May be more plausible to have it return: fourth weekend of october 2017 i.e. October 27- October 30.

**Comment by patapizza** [comment]
Indeed, thanks for reporting @tarung-ml!

**Comment by pcgreat** [comment]
@patapizza say we are trying to create a rule like "last <weekend> of <named-month>", I know we can use "Predicate isAMonth" to capture the month, but not sure how to capture the "weekend". Shall we create a new predicate like "Predicate isWeekend" to do so or is there a better way?

**Comment by patapizza** [comment]
@pcgreat Ideally we would have a notion of weekend in the `Time` internals. This is not straightforward to do, so I would suggest to directly capture "weekend" at the character level (regex), and reuse `ruleWeekend` and `predLastOf` (as in `ruleLastDOWOfTime`).
