### ISSUE TITLE
"what was the weather on Friday" should extract Friday the 16th if today is Wednesday the 21st

### ISSUE THREAD

**Issue by yegeniy** [facebookincubator/duckling#51]
Instead, it seems that we choose the closest Friday (the 23rd).

I realize that detecting this case is a little more complicated than detecting last Friday, since we have to rely on detecting the tense (past) of the sentence, but it would be cool if it is possible.

**Comment by yegeniy** [comment]
Just as a caveat, if the user utters "next Friday" or "in two Friday", we should disregard the tense of the sentence. I think the tense is really only useful in the case of "Friday".

Here are some awkward example sentences:

* what was the weather on Friday: last Friday
* what was the weather last Friday: Friday the 16th

* what **was** the weather **this Friday**: Friday the 23rd
* what is the weather on Friday: Friday the 23rd
* what will the weather be Friday: Friday the 23rd
* what was the weather next Friday: Friday the 30th (or the 23rd, depending on how #44 goes)

**Comment by patapizza** [comment]
Hi @yegeniy,

Indeed, this requires to use full sentence features and is currently outside of the scope of Duckling.
At this point, we only look at the text parsed by the rule (e.g. "Friday", "last Friday", "this Friday", "next Friday").

Closing for now, as there is no plan to support this in the near future.

**Comment by yegeniy** [comment]
That's great to know. I can rely on my own rules in wit.ai without fear of a regression coming in from support for this kind of thing from Duckling.
