### ISSUE TITLE
Clean up Time rules for "ZH" lang

### ISSUE THREAD

**Issue by pcgreat** [facebookincubator/duckling#61]
In "ZH", the Time rules can be updated to sync up with the EN ones. For example, EN rules handles day-of-week and named-month elegantly in one rule, and we can update ZH to use the same approach.
Besides, instead of using the encoded character "\x4e0b", shall we use Chinese character like "份" in the code? It makes things easier for reading, and it works perfect on my local machine.

**Comment by patapizza** [comment]
@pcgreat Indeed, pull requests are welcome! If you're up for it, please do so :-) 

Regarding the encoded characters, we'll try to update them all.

**Comment by patapizza** [comment]
Fixed in https://github.com/facebookincubator/duckling/commit/b3d10dbf05c5066f66908748404c15be80f19a77.
