### ISSUE TITLE
wit/datetime, am/pm vs 24h notation collides at 12 and midnight

### ISSUE THREAD

**Issue by peterel** [facebookincubator/duckling#62]
Hi,

When writing "12" it translates to midnight, i.e. 12:05 becomes 5 minutes past midnight. Since Im using a 24h notation (which works well as 13, 14 etc all work well) Id like 12 to translate to noon. I.e. so 12:05 becomes 5 minutes past noon. How do I go about in doing that?

I.e. how it is today:
<img width="1025" alt="screen shot 2017-07-13 at 20 26 51" src="https://user-images.githubusercontent.com/24371993/28181642-a67ac1d6-6809-11e7-82dc-251e6b8f33e7.png">

**Comment by patapizza** [comment]
Hi @peterel,

One way to deal with this would be to override the 12h rotation assumption (not possible today, #29).

For "today at 12", you can see both midnight and noon in the `values` field. Maybe you can work with that?

**Comment by peterel** [comment]
@patapizza Ok, thanks for the feedback. Ill try doing some workaround on my end I think.
