### ISSUE TITLE
why i run "stack test" under the terminal, it reports "Failed to load interface for ‘Duckling.PhoneNumber.Corpus’",  consequencely, i doubt that the file is missing or the project is still under the developing?

### ISSUE THREAD

**Issue by learnerzhang** [facebookincubator/duckling#63]

**Comment by patapizza** [comment]
Hi @learnerzhang, did you make any changes to the local repo? What is your `stack`/`ghc` versions? From a fresh copy of the repo, the test suite runs just fine.

**Comment by learnerzhang** [comment]
@patapizza thks for replying. after launching the question, I contrast local repo with the original, my local repo did lose the file.  now, it runs ok.
