### ISSUE TITLE
How to handle Lunar holidays

### ISSUE THREAD

**Issue by pcgreat** [facebookincubator/duckling#66]
Holidays like Eid al Fitr and Chinese New Year are lunar holidays, which change every year and no explicit pattern to calculate them out. So I wonder if we can explicitly list out the holiday date for the past and upcoming 10 years, but not sure how to write the rules.

**Comment by patapizza** [comment]
Hi @pcgreat,

Is there an authority providing the data? If so, we can follow what we did for timezones.
Otherwise, a simple `HashMap` can store the information.

**Comment by pcgreat** [comment]
I don't know if there is any authority providing the data. I just get them from https://en.wikipedia.org/wiki/Eid_al-Fitr and https://en.wikipedia.org/wiki/Chinese_New_Year

**Comment by patapizza** [comment]
Ok so the `HashMap` solution seems the way to go.
