### ISSUE TITLE
Extending Duckling for Country specific changes to Rules in Standard Languages

### ISSUE THREAD

**Issue by smaransmarty** [facebookincubator/duckling#7]
I need to add rules for example Indian Holiday rules in time. Where can this be done ??

**Comment by patapizza** [comment]
Hi @smaransmarty,

Today it is not possible to add country-specific rules. So for now I would suggest to add these rules directly in the relevant languages.
For English, the rules would go [here](https://github.com/facebookincubator/duckling/blob/master/Duckling/Time/EN/Rules.hs) and the test examples would go [here](https://github.com/facebookincubator/duckling/blob/master/Duckling/Time/EN/Corpus.hs).

Thanks,
Julien
