### ISSUE TITLE
Identifying where Duckling found the entity (in the text)

### ISSUE THREAD

**Issue by nsanthanam** [facebookincubator/duckling#70]
Hi, 

Duckling is really awesome - thank you for building this tool!

Would it be possible to add the substring in the original text where an entity was detected? (or is this already available?)

For example, a query like `I'm going to visit the US on the first Tuesday of October` provides the response:

`{
  "values": [
    {
      "value": "2017-10-03T00:00:00.000-07:00",
      "grain": "day",
      "type": "value"
    }
  ],
  "value": "2017-10-03T00:00:00.000-07:00",
  "grain": "day",
  "type": "value"
}`

Would it be possible to include `first Tuesday in October` as part of the JSON response? So the response could be:

`{
  "values": [
    {
      "value": "2017-10-03T00:00:00.000-07:00",
      "grain": "day",
      "type": "value"
    }
  ],
  "value": "2017-10-03T00:00:00.000-07:00",
  "text": "first Tuesday of October",
  "grain": "day",
  "type": "value"
}`

where `"text": "first Tuesday of October",` shows which part of the string contained the `Time` entity.

**Comment by patapizza** [comment]
Hi @nsanthanam,

Thank you for the kind words.

Here's what I get when I run locally:
```
$ curl -XPOST http://0.0.0.0:8000/parse --data 'text=the first Tuesday of October'
[{"dim":"time","body":"the first Tuesday of October","value":{"values":[{"value":"2017-10-03T00:00:00.000-07:00","grain":"day","type":"value"}],"value":"2017-10-03T00:00:00.000-07:00","grain":"day","type":"value"},"start":0,"end":28}]
```

At the end, you can see the fields `start` and `end` that you can use to find the matching substring in the original text.

Hope this helps.

**Comment by nsanthanam** [comment]
Thanks for the response - I was able to get it to work!
