### ISSUE TITLE
Feature request - Weight dimensions

### ISSUE THREAD

**Issue by bigman73** [facebookincubator/duckling#75]
Can you please add support for weight dimensions?
For example:
5 oz, 1.5 lbs, 300 mg, 6.2 kg, etc.

Thanks.

**Comment by patapizza** [comment]
Hi @bigman73,

It looks like `Quantity` would work, it just requires to extend the rules to support these examples.
Any chance you can give it a shot?

**Comment by bigman73** [comment]
Hi @patapizza 
Yes, '3 pounds' gets classified as Quantity but the real life examples all resolve to Number.
If you can please extend the rules to support weight quantities (with all their possible permutations and units) then that would be great and will surely contribute to others that need linguistic handling of quantities.

Thanks
