### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by ducdetronquito** [facebookincubator/duckling#76]
Hi everyone !

I failed to find documentation of *duckling*'s API and I am wondering where one can found some, similarly to what can be found at https://duckling.wit.ai/. Any idea ?

Thanks in advance, and have a great day :)

**Comment by patapizza** [comment]
Hi @ducdetronquito,

We are planning on updating `duckling.wit.ai`.
What exactly are you looking for?

**Comment by ducdetronquito** [comment]
Thanks @patapizza, it's a great news :)

General question here, I wasn't looking for something in particular. As I am very new to Haskell, just reading at duckling's code is not enough to understand how things work.

**Comment by blandinw** [comment]
@ducdetronquito https://github.com/facebookincubator/duckling/blob/master/README.md shows the kind of output you get for each dimension, as well as an explanation on how to extend Duckling if you're looking to contribute.

We'll update duckling.wit.ai, but I'm not sure it will have more content than what's in the README + an interactive demo. Feel free to comment on this issue if you have ideas of content we could add!

**Comment by creswick** [comment]
@ducdetronquito the API docs on Hackage are a reasonable place to start.  I'm also new to duckling, but I've used haskell for some time.  You'll find the hackage docs to be a great source of information for most libraries (it adds searchability, indexes, and better navigation through the haddock comments for each library).

Duckling's hackage page is here:  https://hackage.haskell.org/package/duckling

**Comment by ducdetronquito** [comment]
@blandinw + @creswick : Thank you both for your answers :) I didn't know about the Hackage page, which is helpful !

I wanted to start a python binding of duckling, but I have to admit that I need to learn Haskell and improve my C skills first :disappointed:

**Comment by pranjaltale16** [comment]
Hey, 
I need a little help, I was going through the code and came to know that for every `<dimension>/<language>` there exist two files `Rules and Corpus` one consisting of Rules and other for test cases which help us in structuring the query (please correct me if I'm wrong).

I would like to know how a sentence get parsed or How a structured data is generated, is NLP involved behind, if yes, How?
I'm new to Deep learning, so I'm unable to connect much how Rules and Corpus are used in structuring a query. Could you please help me with this part?

Thanks!

**Comment by patapizza** [comment]
Hi @pranjaltale16,

At a high-level, Duckling is a rule engine. As such, it takes a bunch a rules and applies them on an input text; the core logic for this is in [Duckling/Engine.hs](https://github.com/facebook/duckling/blob/master/Duckling/Engine.hs). There is no deep learning involved.

In some cases, multiple valid parses are possible (e.g. "(between 8 and 10) tomorrow" and "between 8 and (10 tomorrow)"). To disambiguate these, we build classifiers based on the `Corpus` examples; this is done in the files you mentioned.

Hope this help.

**Comment by pranjaltale16** [comment]
Yeah, Thanks!!

**Comment by gembin** [comment]
I'm also cannot find useful API doc or user guide, especially for non Haskell users, how duckling can be used.

1. Used as a library?  may be need some programming language bindings?
2. Used as a server provider RESTful API ? I just tried `duckling-example-exe`, but there is no doc about what's the API response JSON format, and what's the meaning of each filed ?

**Comment by mohit-sentieo** [comment]
Hi Guys 

I am planning to put together a document to properly understand Duckling with things like what does a Token, Match etc mean. How does the rule engine work ? How does classifiers work?  I have been learning haskell just because I need to add extra domain specific dimensions to Duckling. Is there anyone else who would like to contribute ?
