### ISSUE TITLE
Quickstart with lang parameter and language detection

### ISSUE THREAD

**Issue by pocman** [facebookincubator/duckling#77]
Hi, 
Thanks a lot for this amazing software !

At first, I was really disappointed by the result I got from the api (with docker), then I discovered the lang parameter... You should probably add it to the quickstart example ;)

Are you planning on adding some language detection mechanism inside the software ?
If it's a no, do you have a preferred tool for language detection ? I might be able to create a new dockerfile that expose the current api but add the lang params if not provided.

Regards,
Thomas Pocreau.

**Comment by patapizza** [comment]
Hi @pocman,

I've updated the example to show how to set the language. The dockerfile runs the server, which already accepts a lang parameter out of the box.

**Comment by pocman** [comment]
Thanks for the update.

My second question was more, do you have a preferred lib as alternative to [Google Language Detector](https://cloud.google.com/translate/docs/detecting-language) ?
I'm looking from something that will feat nicely with duckling and provide the lang params for the current api exposed in the docker image.

In my use case, I don't have previous knowledge of the message's lang.

**Comment by patapizza** [comment]
Sorry I missed that.
I'm not familiar with language detection libraries unfortunately.
