### ISSUE TITLE
Money Parsing Error

### ISSUE THREAD

**Issue by jithurjacob** [facebookincubator/duckling#81]
Hi Guys,

I'm using Duckling in Python using [this](https://github.com/FraBle/python-duckling) library. For me _**1 million dollar**_ and _**0.1 million dollar**_ are returning same response. Could someone please confirm if this is an issue with Duckling or the python library?

Python Library Details

Name: duckling
Version: 1.7.2
Home-page: https://github.com/FraBle/python-duckling
Author: Frank Blechschmidt
Requires: JPype1, six, python-dateutil

Great job on Duckling guys :+1:

**Comment by patapizza** [comment]
Hi @jithurjacob,

This might be specific to the python library, as Duckling does return different values:

```
$ curl -XPOST http://0.0.0.0:8000/parse --data 'text=1 million dollar&lang=en'
[{"dim":"amount-of-money","body":"1 million dollar","value":{"value":1000000,"type":"value","unit":"$"},"start":0,"end":16}]%

$ curl -XPOST http://0.0.0.0:8000/parse --data 'text=0.1 million dollar&lang=en'
[{"dim":"amount-of-money","body":"0.1 million dollar","value":{"value":100000,"type":"value","unit":"$"},"start":0,"end":18}]%
```
