### ISSUE TITLE
What's the reason to choose Monday as the 1st day of a week

### ISSUE THREAD

**Issue by pcgreat** [facebookincubator/duckling#84]
I notice you intentionally pick Monday instead of Sunday to be the first day of a week. May I ask what is the reason behind this design?

**Comment by patapizza** [comment]
I think it's because this is the default in Europe - we weren't used to the US system when we took this assumption. We should be able to override this behavior with #29.

**Comment by chessai** [comment]
FWIW, Even though we aren't going to change this away from Sunday, I think the Europeans got this right :)
