### ISSUE TITLE
How to provide port number

### ISSUE THREAD

**Issue by manikandan-velu** [facebookincubator/duckling#85]
The program is using the default port number(8000), But I need to use my custom port number. Where can I specify that.
Thanks in advance.

**Comment by manikandan-velu** [comment]
You can Specify it in the command line by,
-- -p yourPort

**Comment by Hussein-Dahir** [comment]
thanks !

**Comment by toloco** [comment]
Is this still true?

**Comment by Hussein-Dahir** [comment]
@toloco, -- -p [yourPort]
 I tested it few months ago and it worked, give it a try
