### ISSUE TITLE
Changing the default timezone in Duckling

### ISSUE THREAD

**Issue by nsanthanam** [facebookincubator/duckling#87]
Hello,

I'm trying to change the default timezone from UTC-7 to UTC. I'm totally new to Haskell, so could you help me understand how and where to change the code to do something like this?

**Comment by stopachka** [comment]
Hey @nsanthanam 

You can provide the reference time in the context, when calling parse.

Here's an example: 

```
module Duckling.TimezoneExample
  ( parseText ) where

import Data.Text (Text)

import Duckling.Core
import Duckling.Data.TimeZone

parseText :: Text -> Text -> Lang -> IO [Entity]
parseText text tz lang = do
  tzs <- loadTimeZoneSeries "/usr/share/zoneinfo/"
  refTime <- currentReftime tzs tz
  let
    context = Context
      { referenceTime = refTime
      , lang = lang
      }
  return $ parse text context [This Time]
```

Now if we did `parseText "in 2 minutes" "UTC" EN`

You will get

```
[Entity {dim = "time", body = "in 2 minutes", value = Object (fromList [("values",Array [Object (fromList [("value",String "2017-09-01T19:51:15.246+00:00"),("grain",String "second"),("type",String "value")])]),("value",String "2017-09-01T19:51:15.246+00:00"),("grain",String "second"),("type",String "value")]), start = 0, end = 12}]
```

**Comment by nsanthanam** [comment]
HI @stopachka, I compiled the code that you provided using `:l parseText.hs` (where `parseText.hs` is the filename, stored in the `Duckling` directory) in the `stack` repl (loaded with `stack repl --no-load`) and I see the following error:
```
[316 of 319] Compiling Duckling.Rules   ( /Users/navaneethan/Documents/freshML/duckling/Duckling/Rules.hs, interpreted )
[317 of 319] Compiling Duckling.Api     ( /Users/navaneethan/Documents/freshML/duckling/Duckling/Api.hs, interpreted )
[318 of 319] Compiling Duckling.Core    ( /Users/navaneethan/Documents/freshML/duckling/Duckling/Core.hs, interpreted )
[319 of 319] Compiling Duckling.TimezoneExample ( parseText.hs, interpreted )
parseText.hs:16:9: error: Not in scope: ‘lang’
Failed, modules loaded: Duckling.AmountOfMoney.BG.Rules, ...
...
...
```

It appears that the line `, lang = lang` (line 16) is causing the problem, but I don't understand Haskell well at all, so I'm not sure.

Could you help understand what the issue is?

Steps followed:
`MacBook-Pro-4:Duckling navaneethan$ stack repl --no-load`
`Prelude> :l parseText.hs`

**Comment by nsanthanam** [comment]
Hi @stopachka, I think I've managed to figure out the issue and wanted to see if this was the right way to fix it.
``` 
module Duckling.TimezoneExample
  ( parseText ) where

import Data.Text (Text)


import Duckling.Core
import Duckling.Data.TimeZone
import Duckling.Locale

parseText :: Text -> Text -> Lang -> Maybe Region -> IO [Entity]
parseText text tz lang region = do
  tzs <- loadTimeZoneSeries "/usr/share/zoneinfo/"
  refTime <- currentReftime tzs tz
  let
    context = Context
      { referenceTime = refTime
      , locale = Locale lang (region)
      }
  return $ parse text context [This Time]
```

I made two changes
1. **Line 11**: I changed `parseText :: Text -> Text -> Lang -> IO [Entity]` to `parseText :: Text -> Text -> Lang -> Maybe Region -> IO [Entity]`.
2. **Line 18**: I changed `, lang = lang` to `, locale = Locale lang (region)`

The reason (I think) this works is because `Context` consists of a `referenceTime` and a `locale`, not a `lang`. And `locale` is composed of a `lang` and `region`. I don't yet understand how `Maybe` works, though.

Now the code compiles and when I present it with timezones of the format `Asia/Tbilisi` or `America/Chicago`, it parses the string and returns the time relative to that timezone.

Could you tell me if this is the correct way of doing things? Also, I'm guessing I can expose `parseText` as an API endpoint, but wanted to check.

**Comment by patapizza** [comment]
Hi @nsanthanam, since then we've implemented locales (this is why @stopachka's example isn't working anymore). What you did works, though I would suggest to have `parseText` directly accepts a `Locale`. For an example on how to wrap this into a server, you can look into `exe/ExampleMain.hs`.

**Comment by nsanthanam** [comment]
Excellent thanks for the feedback, I was wondering why the code didn't work. From what you're saying, I can do something like:

```
parseText :: Text -> Text -> Locale -> IO [Entity]
parseText text tz locale = do
  tzs <- loadTimeZoneSeries "/usr/share/zoneinfo/"
  refTime <- currentReftime tzs tz
  let
    context = Context
      { referenceTime = refTime
      , locale = locale
      }
  return $ parse text context [This Time]
```
Here I'm assuming that `locale` is of type `Locale` rather than constructing `Locale` from `lang` and `region`. Is this correct?

How would I have to change my input to reflect this?

Thanks so much for all the help so far, really appreciate it.

**Comment by patapizza** [comment]
That's correct, you'd have to move the locale construction from the function to the callsite.

**Comment by chiapas** [comment]
> Hi @nsanthanam, since then we've implemented locales (this is why @stopachka's example isn't working anymore). What you did works, though I would suggest to have `parseText` directly accepts a `Locale`. For an example on how to wrap this into a server, you can look into `exe/ExampleMain.hs`.

@stopachka, Do you know if the server duckling-example-exe in exe/ExampleMain.hs already support specifying timezone and how? I can't find information I can use.

**Comment by patapizza** [comment]
@chiapas Yes, through the [tz](https://github.com/facebook/duckling/blob/master/exe/ExampleMain.hs#L79) parameter.
