### ISSUE TITLE
Phone numbers parsed as time when prefixed with at

### ISSUE THREAD

**Issue by seme0021** [facebookincubator/duckling#95]
To replicate, replace `xxx-yyy-zzzz` with an actual phone number.

Use cases:
 - `please call me at xxx-yyy-zzzz` returns `{"dim":"time"`
 - `please call me xxx-yyy-zzzz` returns `{"dim":"phone-number"`

A huge fan of the library but don't know Haskell well enough to fix on my own.

**Comment by patapizza** [comment]
Thanks for reporting @seme0021. I'll look into this.
