### ISSUE TITLE
Should have more logical am/pm defaults when am/pm not specified

### ISSUE THREAD

**Issue by seme0021** [facebookincubator/duckling#97]
Not sure if the following type of logic should live within duckling (but would be nice):
 - User says `tomorrow at 1` and does not specify `am/pm`
 - Duckling currently assumes `am`

I would argue that there are more cases where the user means `pm` rather than `am` and that should be the default for values `1 - 5`.

Thoughts?

**Comment by patapizza** [comment]
Duckling returns the first future value in the `value` field, and the first 3 future values in the `values` field.
For `tomorrow at 1`, it returns both `tomorrow at 1am` and `tomorrow at 1pm` in `values`.

To override the behavior of `value`, we'll need to figure out #29.
Until then, I would suggest to implement a custom filtering on the returned `values` based on your business logic.
